services:
  auth-service:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    build: ./Auth-ToDo
    ports:
      - "10000:10000"
    networks:
      - my-network
  
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:80"
  #   depends_on:
  #     - auth-service
  #   networks:
  #     - my-network
  #   environment:
  #     - VITE_API_URL=http://auth-service:10000 


networks:
  my-network:
    driver: bridge