services:
  auth-service:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    build: ./Auth-ToDo
    ports:
      - "10000:10000"
    networks:
      - my-network
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge